package com.cloud.secure.streaming.common.enums;

public enum FeedbackType {
    FULL_COURSE,COURSE_LADING_PAGE,INTENDED_LEARNERS,CURRICULUM,COURSE_PREVIEW, LANGUAGE_CAPTION,PRICING,PROMOTION,ANNOUNCEMENTS
}
